login_server_ip: db
login_server_port: 3306
login_server_id: ${RATHENA_DB_USER}
login_server_pw: ${RATHENA_DB_PASSWORD}
login_server_db: ${RATHENA_DB_NAME}
ipban_db_ip: db
ipban_db_port: 3306
ipban_db_id: ${RATHENA_DB_USER}
ipban_db_pw: ${RATHENA_DB_PASSWORD}
ipban_db_db: ${RATHENA_DB_NAME}
char_server_ip: db
char_server_port: 3306
char_server_id: ${RATHENA_DB_USER}
char_server_pw: ${RATHENA_DB_PASSWORD}
char_server_db: ${RATHENA_DB_NAME}
map_server_ip: db
map_server_port: 3306
map_server_id: ${RATHENA_DB_USER}
map_server_pw: ${RATHENA_DB_PASSWORD}
map_server_db: ${RATHENA_DB_NAME}
log_db_ip: db
log_db_port: 3306
log_db_id: ${RATHENA_DB_USER}
log_db_pw: ${RATHENA_DB_PASSWORD}
log_db_db: ${RATHENA_DB_NAME}
